### ISSUE TITLE
Have WAS work with Polyglot module [Feature Request]

### ISSUE THREAD

**Issue by kiloforce** [WilStead/FoundryVTT.WhisperAs#1]
Want to send intimidating-sounding cryptic messages to individual characters - classic language barrier misunderstanding, but the standard whisper interface is clunky, and the message doesn't appear to come from the correct token character. The WhisperAs module helps with the kunkly and the correct character part.  But if using Polyglot, it doesn't come across encoded.

---

Standard example: typing out character name is painful (sadness), but message comes across encoded (happiness), but comes from the "DM" character instead of the selected Goblin token (sadness):
![image](https://github.com/WilStead/FoundryVTT.WhisperAs/assets/433058/db1ff849-6a62-4612-95ae-54788d49823b)

---

WAS example:
![image](https://github.com/WilStead/FoundryVTT.WhisperAs/assets/433058/ce27011b-a7c9-4ad1-a261-b37b354d4a80)

Easy target selection (hapiness), and message comes across from the correct character (Goblin - happiness), but non encoded (sadness):
![image](https://github.com/WilStead/FoundryVTT.WhisperAs/assets/433058/887a2590-6581-46f9-92f9-1317753d2277)

**Comment by WilStead** [comment]
Excellent suggestion!

I have just released [v1.2.0](https://github.com/WilStead/FoundryVTT.WhisperAs/releases/tag/v1.2.0) with Polyglot compatibility.
